CREATE TABLE IF NOT EXISTS preset_activities (
  id         CHAR(36)      NOT NULL PRIMARY KEY,
  emoji      VARCHAR(10)   NOT NULL,
  label      VARCHAR(100)  NOT NULL,
  image_path VARCHAR(500)  NOT NULL,
  ring       TINYINT UNSIGNED NOT NULL,
  sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  version    INT UNSIGNED  NOT NULL DEFAULT 0,
  created_at DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS activities (
  id         CHAR(36)      NOT NULL PRIMARY KEY,
  profile_id CHAR(36)      NOT NULL,
  preset_id  CHAR(36)      DEFAULT NULL,
  emoji      VARCHAR(10)   NOT NULL,
  label      VARCHAR(100)  NOT NULL,
  from_hour  TINYINT UNSIGNED NOT NULL,
  to_hour    TINYINT UNSIGNED NOT NULL,
  ring       TINYINT UNSIGNED NOT NULL,
  image_path VARCHAR(500)  NOT NULL,
  sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  version    INT UNSIGNED  NOT NULL DEFAULT 0,
  created_at DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
  FOREIGN KEY (preset_id)  REFERENCES preset_activities(id) ON DELETE SET NULL
);
