CREATE TABLE IF NOT EXISTS profiles (
  id         CHAR(36)     NOT NULL PRIMARY KEY,
  child_id   CHAR(36)     NOT NULL,
  name       VARCHAR(100) NOT NULL,
  color      VARCHAR(20)  NOT NULL DEFAULT '#e07a3a',
  version    INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME     NULL,
  FOREIGN KEY (child_id) REFERENCES children(id) ON DELETE CASCADE
);
